### ISSUE TITLE
Remove the language filter on ODC's law's pages?

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_tabular_pages#38]
@prustar @tthy has suggested the following:

> Remove the language filter

![screenshot from 2016-12-08 10-04-58](https://cloud.githubusercontent.com/assets/384894/21003856/cda4c96e-bd2d-11e6-8698-20c44673237a.png)

In my opinion we should not remove the language filter but limit the options presented on it to those languages for which laws are currently available, otherwise we are reducing the filtering possibilities since there are laws in English, In Khmer and/or both.

Please provide comments

**Comment by acorbi** [comment]
@prustar @tthy FYI: I have implemented https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/issues/48 which is basically my suggestion of _ not remove the language filter but limit the options presented on it to those languages for which laws are currently available_

Please test on PP: https://pp.opendevelopmentcambodia.net/tabular/laws/?query=&language=en&taxonomy=all

**Comment by prustar** [comment]
@acorbi -- Language filter at country site level should only apply to the **resources (language)** and not the metadata forms as these should all be available in both languages and be selected when you use the language switcher. 

@tthy -- I've noted that many of the law metadata forms are still not translated into Khmer.

**Comment by Huyeng** [comment]
@acorbi - after discussion with the team, we don't need the language filter because it doesn't give much value to ODC. Moreover, the language filter doesn't work properly, even the English is filtered, but Khmer documents are still shown up (see the screenshot). That may be the editorial issue. 

Reply to the law that are translated, I tried to recall how the law is migrated from the WP, but I didn't get clearly, could you please describe again pls? On WP all the laws are available in Khmer and English.

![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/21338930/2423acd2-c6ad-11e6-8621-8e92b40eb932.jpg)
https://opendevelopmentcambodia.net/km/tabular/laws-profiles-and-agreements/?query=&language=en&taxonomy=all

**Comment by acorbi** [comment]
@Huyeng yeah, some records have English as language, but others have both English and Khmer. it is in part an editorial inconsistency. FYI @prustar .

If we remove that filter, then users cannot filter by language anymore. For instance, in order to get only records in Khmer and not in English.

>I tried to recall how the law is migrated from the WP, but I didn't get clearly, could you please describe again pls?

Laws were automatically migrated from NGL to CKAN by using migration scripts that would take the available metadata and resources and create one CKAN record with them. If there was a law both in Khmer and english, 2 records would then be created (one in english and the other one in khmer)


![screenshot from 2016-12-20 10-42-24](https://cloud.githubusercontent.com/assets/384894/21345556/02f5a3f0-c6a1-11e6-827e-650ab6f3dae5.png)

**Comment by Huyeng** [comment]
@acorbi - Laws are stored on the WP, but library records are in the NGL. 
> Laws were automatically migrated from NGL to CKAN 

I just wonder why there are about 500 records have not translated in Khmer because the editors ensured the laws in old site are completely translated. I used to export the xml files of law both English and Khmer for migration. Can you recall this?

Well, from our perspective, filter function by language is not useful, but by year or document type is very important than.  There is sort function of table that can use if they are looking for the English or Khmer.
> If we remove that filter, then users cannot filter by language anymore. For instance, in order to get only records in Khmer and not in English.

**Comment by acorbi** [comment]
@Huyeng apologies, I said Laws when I meant Library records. let me correct my statement:

- Laws were automatically migrated from old ODC to new site via scripts
- Records in Khmer and records in English were migrated individually because back then we did not have any multilingual support for CKAN records

I believe @prustar coordinated the unification of those records into single ones some months ago. It would be good to analize which records are still in a inconsistent state and make sure the metadata is correctly specified.

**Comment by prustar** [comment]
@acorbi @Huyeng -- I don't specifically remember doing this migration? But I remember that we had to at some point. On the system you would have been able to identify the corresponding English and Khmer records to be able to match and merge them. In that case why then would a random number of 543 law records be missed? And now I've discovered some inconsistencies in this as well? See hackpad notes. https://hackpad.com/Meeting-on-CKAN-Law-and-Library-Records-2016-1221-ubNmsL8B0tg

Can we investigate what happened here and perhaps find any other records that have this issue. If we can find an automated record to update these 543 records then great - if not then the editors need to update manually. @ChandaraKhun

**Comment by acorbi** [comment]
@prustar @Huyeng with the current implementation. each team can determine which filters appear on the laws pages (tabular pages). See https://wiki.opendevelopmentmekong.net/partners:tabular_pages#configuring_default_and_additional_filters

This issue is solved and therefore can be closed. Identifying inconsistencies of Laws records on CKAN should be approached separately.
